version: '3.7'
services:
  transactionaltracker:
    restart: always
    build: .
    ports:
      - 8081:8081
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/code
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis"
    ports:
      - "6379:6379"